version: '3.9'

services:
  db:
    build: ./database
    environment:
      MYSQL_DATABASE: proj_db
      MYSQL_USER: proj_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql2:/var/lib/mysql
    networks:
      - net_bridge
  http_server:
    depends_on:
      - db
    build: ./server
    environment:
      SESSION_SECRET: PP72b4L68gUVIScKgVydrXpKy+A=
    ports:
      - 8080:8080
    networks:
      - net_bridge
    volumes:
      - ./server:/app
    restart: on-failure
  db_admin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - net_bridge

volumes:
  mysql2:

networks:
  net_bridge:
    driver: bridge
