version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: proj_db
      MYSQL_USER: proj_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - net_bridge
  http_server:
    depends_on:
      - db
    build: ./server
    ports:
      - 80:8080
    networks:
      - net_bridge
    volumes:
      - ./server:/app
  db_admin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - net_bridge

volumes:
  mysql:

networks:
  net_bridge:
    driver: bridge
